AWSTemplateFormatVersion: 2010-09-09

Description: Manager template for pipeline

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
  SubnetA:
    Type: AWS::EC2::Subnet::Id
  SubnetB:
    Type: AWS::EC2::Subnet::Id  
  GithubAuthToken:
    Type: String
    Description: "Token used by codepipeline to verify if the incoming event comes from the github repo"
    MaxLength: 100
    MinLength: 0
    NoEcho: true
    # AllowedPattern: "[a-z0-9]*"
  GithubBranch:
    Type: String
    Description: "Pipeline branch"
  GithubAccount:
    Type: String
    Description: "Github accound name"
  GithubRepository:
    Type: String
    Description: "Github repository name"
  TemplateBucket:
    Type: String
    Default: pipeline-manager
    Description: >
      The S3 bucket from which to fetch the templates used by this stack.

Metadata:
  AWS::CloudFormation::Interface:
    ParameterLabels:
      GithubBranch:
        default: "main"
      GithubAuthToken:
        default: "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"
      GithubAccount:
        default: "Alexeanred"
      GithubRepository:
        default: "aws-automation-CI-CD"
      VpcId:
        default: "vpc-a8e395c3" 
      SubnetA:
        default: "subnet-22049a49"
      SubnetB:
        default: "subnet-91b463ec"
    ParameterGroups:
      - Label:
          default: GitHub Configuration    
        Parameters:
          - GithubBranch
          - GithubAuthToken
          - GithubAccount
          - GithubRepository
      - Label:
          default: Stack Configuration
        Parameters:
          - TemplateBucket
      - Label:
          default: VPC Configuration
        Parameters:
          - VpcId
          - SubnetA
          - SubnetB
Resources:
  ALB_TG_ECS: 
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${TemplateBucket}/templates/test-alb-tg-ecs.yml"   
      Parameters:
        VpcId: !Ref VpcId
        SubnetA: !Ref SubnetA
        SubnetB: !Ref SubnetB
        Image: !GetAtt CodePipeline_ECR.Outputs.ECRImageUri

  CodePipeline_ECR: 
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${TemplateBucket}/templates/pipeline.yml"   
      Parameters: 
        GithubAuthToken: !Ref GithubAuthToken
        GithubAccount: !Ref GithubAccount
        GithubRepository: !Ref GithubRepository
        GithubBranch: !Ref GithubBranch
        Cluster: !GetAtt ALB_TG_ECS.Outputs.ClusterName
        Service: !GetAtt ALB_TG_ECS.Outputs.ServiceName

Outputs:
  WebApp:
    Description: Web app DNS from LB
    Value: !GetAtt ALB_TG_ECS.Outputs.LoadBalancerDNS

  PipelineUrl:
    Description: CodePipeline from AWS Console
    Value: !GetAtt CodePipeline_ECR.Outputs.PipelineUrl